# Generated by Django 5.2.1 on 2025-05-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_badge_studentbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='learning.module'),
        ),
    ]
