# Generated by Django 5.2.1 on 2025-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/makbig.png', null=True, upload_to='profile_pics/'),
        ),
    ]
